include(GNUInstallDirs)
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY
    ${PROJECT_BINARY_DIR}/${CMAKE_INSTALL_LIBDIR})
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY
    ${PROJECT_BINARY_DIR}/${CMAKE_INSTALL_LIBDIR})
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY
    ${PROJECT_BINARY_DIR}/${CMAKE_INSTALL_BINDIR})

set(BGMRPC_REMOTE
    "${CMAKE_INSTALL_PREFIX}/BGMRPC${REMOTE_DIR}"
    CACHE STRING "")
set(BGMRPC_CLIENT
    "${CMAKE_INSTALL_PREFIX}/BGMRPC${CLIENT_DIR}"
    CACHE STRING "")

add_definitions(-DREMOTEPATH="${BGMRPC_REMOTE}")
add_definitions(-DCLIENTPATH="${BGMRPC_REMOTE}")
add_definitions(
  -DDEFAULT_ETC_DIR="${BGMRPC_REMOTE}/${CMAKE_INSTALL_DATADIR}/etc")

set(BGMRPCCommon_includeDir
    ${CMAKE_SOURCE_DIR}/BGMRPCCommon
    CACHE PATH "")
set(BGMRPCObjectInterface_includeDir
    ${CMAKE_SOURCE_DIR}/BGMRPCObjectInterface
    CACHE PATH "")
