include(GNUInstallDirs)
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY
    ${PROJECT_BINARY_DIR}/${CMAKE_INSTALL_LIBDIR})
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY
    ${PROJECT_BINARY_DIR}/${CMAKE_INSTALL_LIBDIR})
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY
    ${PROJECT_BINARY_DIR}/${CMAKE_INSTALL_BINDIR})

set(BGMRPC_REMOTE
    "${CMAKE_INSTALL_PREFIX}/BGMRPC/${REMOTE_DIR}"
    CACHE STRING "")
set(BGMRPC_CLIENT
    "${CMAKE_INSTALL_PREFIX}/BGMRPC/${CLIENT_DIR}"
    CACHE STRING "")

set(BGMRPCCommon_includeDir
    ${CMAKE_CURRENT_LIST_DIR}/../BGMRPCCommon
    CACHE PATH "")
set(BGMRPCObjectInterface_includeDir
    ${CMAKE_CURRENT_LIST_DIR}/../BGMRPCObjectInterface
    CACHE PATH "")

set(BGMRPC_VERSION_MAJOR 1)
set(BGMRPC_VERSION_MINOR 0)
set(BGMRPC_VERSION_PATCH 2)

set(BGMRPC_VERSION
    "${BGMRPC_VERSION_MAJOR}.${BGMRPC_VERSION_MINOR}.${BGMRPC_VERSION_PATCH}"
    CACHE INTERNAL "BGMRPC AND CHILD PRJS version")
