set(BGMRPC_VERSION_MAJOR 1)
set(BGMRPC_VERSION_MINOR 0)
set(BGMRPC_VERSION_PATCH 2)

set(BGMRPC_VERSION
    "${BGMRPC_VERSION_MAJOR}.${BGMRPC_VERSION_MINOR}.${BGMRPC_VERSION_PATCH}"
    CACHE INTERNAL "BGMRPC AND CHILD PRJS version")
